import bpy
import os

def export_to_obj():
    output_path = "C:\\Users\\mrkri\\Documents\\RTGC-1.0\\assets\\models\\uaz_model.obj"

    obj_file = open(output_path, 'w')
    obj_file.write("# RTGC UAZ Model OBJ Export\n")
    obj_file.write("# Generated by Blender\n\n")

    vertex_offset = 1

    for obj in bpy.data.objects:
        if obj.type != 'MESH':
            continue

        mesh = obj.data
        matrix = obj.matrix_world

        obj_file.write(f"# Object: {obj.name}\n")

        for vert in mesh.vertices:
            world_pos = matrix @ vert.co
            obj_file.write(f"v {world_pos.x:.6f} {world_pos.y:.6f} {world_pos.z:.6f}\n")

        for vert in mesh.vertices:
            n = vert.normal
            world_normal = matrix.to_3x3() @ n
            obj_file.write(f"vn {world_normal.x:.6f} {world_normal.y:.6f} {world_normal.z:.6f}\n")

        for poly in mesh.polygons:
            if len(poly.vertices) == 3:
                v1 = poly.vertices[0] + vertex_offset
                v2 = poly.vertices[1] + vertex_offset
                v3 = poly.vertices[2] + vertex_offset
                obj_file.write(f"f {v1}//{v1} {v2}//{v2} {v3}//{v3}\n")

        vertex_offset += len(mesh.vertices)

    obj_file.close()
    print(f"Exported to: {output_path}")
    return output_path

if __name__ == "__main__":
    export_to_obj()